# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 529)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        Form.setFont(font)
        self.btn_topla = QtWidgets.QPushButton(parent=Form)
        self.btn_topla.setGeometry(QtCore.QRect(350, 190, 111, 41))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(parent=Form)
        self.btn_cikar.setGeometry(QtCore.QRect(350, 240, 111, 41))
        self.btn_cikar.setObjectName("btn_cikar")
        self.txt_sayi1 = QtWidgets.QLineEdit(parent=Form)
        self.txt_sayi1.setGeometry(QtCore.QRect(110, 50, 141, 41))
        self.txt_sayi1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_sonuc = QtWidgets.QLabel(parent=Form)
        self.label_sonuc.setGeometry(QtCore.QRect(20, 300, 71, 31))
        self.label_sonuc.setObjectName("label_sonuc")
        self.btn_carp = QtWidgets.QPushButton(parent=Form)
        self.btn_carp.setGeometry(QtCore.QRect(350, 290, 111, 41))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bol = QtWidgets.QPushButton(parent=Form)
        self.btn_bol.setGeometry(QtCore.QRect(350, 340, 111, 41))
        self.btn_bol.setObjectName("btn_bol")
        self.lineSonuc = QtWidgets.QLineEdit(parent=Form)
        self.lineSonuc.setGeometry(QtCore.QRect(20, 340, 113, 61))
        self.lineSonuc.setObjectName("lineSonuc")
        self.btn_yeni_sayi = QtWidgets.QPushButton(parent=Form)
        self.btn_yeni_sayi.setGeometry(QtCore.QRect(330, 40, 111, 41))
        self.btn_yeni_sayi.setObjectName("btn_yeni_sayi")
        self.btn_son_sayi_kaldir = QtWidgets.QPushButton(parent=Form)
        self.btn_son_sayi_kaldir.setGeometry(QtCore.QRect(330, 90, 111, 41))
        self.btn_son_sayi_kaldir.setObjectName("btn_son_sayi_kaldir")
        self.tbl_sayilar = QtWidgets.QTableWidget(parent=Form)
        self.tbl_sayilar.setGeometry(QtCore.QRect(110, 100, 141, 221))
        self.tbl_sayilar.setObjectName("tbl_sayilar")
        self.tbl_sayilar.setColumnCount(0)
        self.tbl_sayilar.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_topla.setText(_translate("Form", "Topla"))
        self.btn_cikar.setText(_translate("Form", "Çıkar"))
        self.txt_sayi1.setPlaceholderText(_translate("Form", "1. Sayı Gir"))
        self.label.setText(_translate("Form", "1. Sayı"))
        self.label_2.setText(_translate("Form", "2. Sayı"))
        self.label_sonuc.setText(_translate("Form", "SONUÇ"))
        self.btn_carp.setText(_translate("Form", "Çarp"))
        self.btn_bol.setText(_translate("Form", "Böl"))
        self.btn_yeni_sayi.setText(_translate("Form", "Yeni sayı ekle"))
        self.btn_son_sayi_kaldir.setText(_translate("Form", "Son sayıyı Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
